name: Upload to NuGet

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - run: dotnet build --configuration Release Devris.LibDevris.MethodSinter
      - name: Create the package
        run: dotnet pack --configuration Release Devris.LibDevris.MethodSinter
      - name: Publish the package to GPR
        run: dotnet nuget push Devris.LibDevris.MethodSinter/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
